Sprint 7 solution in file manager
Danil21/praktikum pull request #1
Opened 2024-03-14 20:08 UTC by Danil21

adding a save function to a file

2024-03-15 17:23 UTC, YazykovMikhail reviewed
Не вижу прикрепленного файла для сохранения.
Стоит в коне создать папку resources и создать там файл например
task.csv

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    private static final String HEADER_CSV_FILE = "id,type,name,status,description,startTime,duration,epicId\n";
статические переменные обьявляются первыми
Не стоит делать перено строки в конце, переменная же отвечает за хедеры, кому нужно сами поставят перенос
Тем более в разных системах перенос делается по разному

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    private File file;
Стоит добавить final
файл во время работы приложения не должен меняться

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/tasks/Epic.java
> +    private Instant endTime;
хм, вроде бы в 7 задание про это нет ничего

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/tasks/Task.java
> +    private Instant startTime;
вроде бы в 7 задание про это нет ничего

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/tasks/Task.java
> +    private long duration;
вроде бы в 7 задание про это нет ничего

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    public void save() {
```
protected void save() {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
			writer.write(CSVTaskFormat.getHeader());
			writer.newLine();

			for (Map.Entry<Integer, Task> entry : tasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Subtask> entry : subtasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Epic> entry : epics.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			writer.newLine();
			writer.write(CSVTaskFormat.toString(historyManager));
			writer.newLine();
		} catch (IOException e) {
			throw new ManagerSaveException("Can't save to file: " + file.getName(), e);
		}
	}
```
Как уже писал выше, лучше испольщовать автоматически определяющийся перевод строки, в разных операционных системах он разный.
Так же лучше использовать буферизацию для оптимизации ресурсов

2024-03-15 17:23 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +public class FileBackedTasksManager extends InMemoryTaskManager {
Все методы из пункта "Как сохранять задачи в файл и считывать их из него"
стоит вынести в утилитный класс CSVTaskFormat

2024-03-15 17:25 UTC, YazykovMikhail reviewed
Так же стоит поправть класс 
```
public class Managers {
	public static TaskManager getDefault() {
		return new FileBackedTaskManager(new File("resources/task.csv"));
	}

	public static HistoryManager getDefaultHistory() {
		return new InMemoryHistoryManager();
	}
}
```
теперь работа поумолчнию будет с файлом

2024-03-15 17:40 UTC, YazykovMikhail requested changes

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/tasks/Task.java
Стоит отдельно добавить
public enum TaskType {
	TASK, SUBTASK, EPIC
}
и в задаче стоит или поле TaskType type
или сделать в каждой задаче метод:
public TaskType getType() {
		return TaskType.TASK;
	}
	который будет возвращать соотвествующий тип для каждый. Что бы можно было идентифицировать задачу

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    public void loadFromFile() {
Задачи должны не создаваться новый, а считываться старые и возвращатсья состояние. Так же стоит возвращать историю. Сейчас у тебя задачи создаются через стандарные методы создания, но там устанавливабтся новые id, а нам нужно именно старое состоние, стоит записывать напрямую в хранилище считанные задачи:
СПОЛЙЕР:
```
public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			List<Integer> history = Collections.emptyList();
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					history = CSVTaskFormat.historyFromString(lines[i + 1]);
					break;
				}
				final Task task = CSVTaskFormat.taskFromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			for (Integer taskId : history) {
				taskManager.historyManager.add(taskManager.findTask(taskId));
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}
```
Так же понадобятся вспомогательные методы:
```
protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}

	protected Task findTask(Integer id) {
		final Task task = tasks.get(id);
		if (task != null) {
			return task;
		}

		final Subtask subtask = subtasks.get(id);
		if (subtask != null) {
			return subtask;
		}

		return epics.get(id);
	}
```

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    static String historyToString(HistoryManager manager) {
Чтобы не делать эту дополнительную проверку, можно сделать вот так:
```
public static String toString(HistoryManager historyManager) {
		final List<Task> history = historyManager.getHistory();
		if (history.isEmpty()) {
			return "";
		}

		StringBuilder sb = new StringBuilder();
		sb.append(history.get(0).getId());
		for (int i = 1; i < history.size(); i++) {
			Task task = history.get(i);
			sb.append(",");
			sb.append(task.getId());
		}
		return sb.toString();
	}
```

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    static String historyToString(HistoryManager manager) {
Напомню что все методы из пункта"Как сохранять задачи в файл и считывать их из него" стоит вынести в класс CSVTaskFormat который будет отвечать за конвертации

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    private String toString(Task task) {
Как нибудь так будет попроще:

```
public static String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? task.getEpicId() : "");
	}
```

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +        } else if (type.equals("Subtask")) {
Вот как раз что бы не сравнивать с какими то строками, стоит сразу выделить типы задач в enum
TaskType.SUBTASK
и обрати внимание, что в задании они написаны заглавными буквами

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +            epic.setId(id);
добавь конструкторы на все поля, чтобы не делать такие сеты

2024-03-15 17:40 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTasksManager.java
> +    private static final String HEADER_CSV_FILE = "id,type,name,status,description,startTime,duration,epicId\n";
вынеси тоже в класс
CSVTaskFormat

2024-03-15 17:41 UTC, YazykovMikhail commented
Что бы получить прямой доступ из класса наследника до полей родителя, стоит в классе InMemoryTaskManager сделать все поля: protected

2024-03-17 10:53 UTC, YazykovMikhail requested changes

2024-03-17 10:53 UTC, YazykovMikhail commented on src/main/java/manager/InMemoryTaskManager.java
>      private int idTask = 0;
тоже стоит сделать  protected, что бы установить это занчение при восстановлении состояния

2024-03-17 10:53 UTC, YazykovMikhail commented on src/main/java/manager/FileBackedTaskManager.java
> +              // taskManager.getId()  = generatorId;
поле idTask стоит сделать protected 
idTask = generatorId;
Ведь когда программа восстановит состояние, счетчик id долден продолжится, а не начатсья с 0, ведь задачи которые будут в программе уже будут иметь идентификаторы из предыдущего сеанса работы.

2024-03-17 14:03 UTC, YazykovMikhail approved these changes

2024-03-19 11:16 UTC, Danil21 commented
fix

2024-03-19 11:16 UTC, Danil21 commented
fix

2024-03-19 11:17 UTC, merged